
import React,{Component} from 'react';
import DetailItem from '../components/DetailItem';


class Detailpos extends Component{
	constructor(){
		super();
		this.state={
			"posList":[
			{
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3237453,
                            "positionName":"Java工程师",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"15k-30k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":496417,
                            "positionName":"高级数据挖掘工程师",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"20k-40k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3698541,
                            "positionName":"机器学习（校招）",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"18k-30k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3698977,
                            "positionName":"Java（校招）",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"10k-20k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3697533,
                            "positionName":"Java开发工程师（web方向）",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"18k-36k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3697698,
                            "positionName":"java开发工程师（校招）",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"10k-18k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3529978,
                            "positionName":"前端开发工程师",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"15k-30k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3237571,
                            "positionName":"前端工程师",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"15k-30k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3754290,
                            "positionName":"Web前端开发工程师",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"18k-25k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3754341,
                            "positionName":"JAVA后端开发",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"15k-25k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3712540,
                            "positionName":"前端（校招）",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"10k-20k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        },
                        {
                            "logger":{
                                "traceCapable":true,
                                "name":"com.lagou.entity.mobile.MobilePosition"
                            },
                            "positionId":3712490,
                            "positionName":"java（校招）",
                            "city":"北京",
                            "createTime":"2017-10-30",
                            "salary":"10k-20k",
                            "companyId":147,
                            "companyLogo":"i/image/M00/76/40/Cgp3O1g1TNOAB2yxAAA9bQUyc4g814.png",
                            "companyName":"拉勾网",
                            "companyFullName":"北京拉勾网络技术有限公司"
                        }
			]
		}
	}

	render(){
		 var poslist=this.state.posList.map(function(positem,index){
    			return <DetailItem poses={positem} key={positem.index}  />
    		})
		return(
			<ul className="list">
                {poslist}
            </ul>
			)
	}
}
export default Detailpos;